### ISSUE TITLE
Why is this printing when I run the file in qtcreator ? " CPU usage is -nan% "

### ISSUE THREAD

**Issue by roswi2107** [doleron/cpp-linux-system-stats#1]

**Comment by doleron** [comment]
Sorry, without seeing your code I cannot realize what is happening there. Can you provide more evidence?

**Comment by roswi2107** [comment]
Actually that Issue was solved , There is a waiting period right for cpu,
that was missing  ,I just add the 100 mili seconds sleep for that thread
and it worked!!

**Comment by doleron** [comment]
Oh, I see. I'm glad to know you have fixed your problem. Good coding.
